// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FitCallLocal_fun_Rcpp
SEXP FitCallLocal_fun_Rcpp(SEXP& bppass_x_inn, SEXP& ChromInf_inn);
RcppExport SEXP _MACPET_FitCallLocal_fun_Rcpp(SEXP bppass_x_innSEXP, SEXP ChromInf_innSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type bppass_x_inn(bppass_x_innSEXP);
    Rcpp::traits::input_parameter< SEXP& >::type ChromInf_inn(ChromInf_innSEXP);
    rcpp_result_gen = Rcpp::wrap(FitCallLocal_fun_Rcpp(bppass_x_inn, ChromInf_inn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MACPET_FitCallLocal_fun_Rcpp", (DL_FUNC) &_MACPET_FitCallLocal_fun_Rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MACPET(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
