# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FitCallLocal_fun_Rcpp <- function(bppass_x_inn, ChromInf_inn) {
    .Call('_MACPET_FitCallLocal_fun_Rcpp', PACKAGE = 'MACPET', bppass_x_inn, ChromInf_inn)
}

