# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FilterFastqYield_fun_Rcpp <- function(Curfastqyieldsize, SreadFastq1, WidthSreadFastq1, SreadFastq2, WidthSreadFastq2, S0_LinkerA, S0_LinkerB, S0_LinkerOccurence, S0_MinReadLength, S0_MaxReadLength) {
    .Call('_MACPET_FilterFastqYield_fun_Rcpp', PACKAGE = 'MACPET', Curfastqyieldsize, SreadFastq1, WidthSreadFastq1, SreadFastq2, WidthSreadFastq2, S0_LinkerA, S0_LinkerB, S0_LinkerOccurence, S0_MinReadLength, S0_MaxReadLength)
}

FitCallLocal_fun_Rcpp <- function(bppass_x, ChromInf) {
    .Call('_MACPET_FitCallLocal_fun_Rcpp', PACKAGE = 'MACPET', bppass_x, ChromInf)
}

